// Mock data for development - remove when backend is implemented
export const mockNotes = [
  {
    id: "1",
    user_id: "mock-user",
    study_area_id: "mock-area-1",
    category_id: "cat-1",
    title: "Introduction to Machine Learning",
    content: "Machine learning is a subset of artificial intelligence (AI) that focuses on developing algorithms and statistical models that enable computers to improve their performance on a specific task through experience.",
    summary: "ML is AI subset focusing on algorithms that improve through experience.",
    note_type: "cornell" as const,
    tags: ["machine-learning", "ai", "introduction"],
    questions: ["What is machine learning?", "How does ML relate to AI?"],
    connections: ["relates to artificial intelligence", "basis for deep learning"],
    confidence_level: 4,
    review_frequency: 3,
    is_favorite: false,
    word_count: 35,
    reading_time: 1,
    difficulty: 3,
    repetition_count: 2,
    next_review_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    last_reviewed_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    user_id: "mock-user",
    study_area_id: "mock-area-1",
    category_id: "cat-1",
    title: "Types of Learning Algorithms",
    content: "Supervised Learning: Uses labeled data to train models. Examples: Classification, Regression. Unsupervised Learning: Finds patterns in unlabeled data. Examples: Clustering, Dimensionality reduction.",
    summary: "Two main types: Supervised (labeled data) and Unsupervised (unlabeled data).",
    note_type: "concept_map" as const,
    tags: ["supervised", "unsupervised", "algorithms"],
    questions: ["What is supervised learning?", "What is unsupervised learning?"],
    connections: ["builds on ML fundamentals", "applies to classification problems"],
    confidence_level: 3,
    review_frequency: 2,
    is_favorite: true,
    word_count: 28,
    reading_time: 1,
    difficulty: 2,
    repetition_count: 1,
    next_review_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    last_reviewed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    user_id: "mock-user",
    study_area_id: "mock-area-1",
    category_id: "cat-2",
    title: "Linear Regression Formula",
    content: "y = mx + b\n\nWhere:\n- y = dependent variable (output)\n- m = slope of the line\n- x = independent variable (input)\n- b = y-intercept",
    summary: "Linear relationship formula with slope and intercept.",
    note_type: "flashcard" as const,
    tags: ["linear-regression", "formula", "mathematics"],
    questions: ["What is the linear regression formula?", "What does each variable represent?"],
    connections: ["fundamental to regression analysis", "basis for more complex models"],
    confidence_level: 5,
    review_frequency: 7,
    is_favorite: false,
    word_count: 22,
    reading_time: 1,
    difficulty: 1,
    repetition_count: 4,
    next_review_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    last_reviewed_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const mockCategories = [
  {
    id: "cat-1",
    user_id: "mock-user",
    name: "Concepts",
    description: "Main concepts and theories",
    color: "#3B82F6",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    user_id: "mock-user",
    name: "Formulas",
    description: "Mathematical formulas and equations",
    color: "#F59E0B",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    user_id: "mock-user",
    name: "Examples",
    description: "Practical examples and applications",
    color: "#10B981",
    created_at: new Date().toISOString(),
  }
];
